### ISSUE TITLE
Allow chrome suggested passwords

### ISSUE THREAD

**Issue by anulaibar** [AnaBoscaneanu/RecipesApp#1]
Great app @AnaBoscaneanu !

I added my favourite tomato salad recipe :)

One suggested improvement would be to allow chrome generated passwords (I think you currently require special characters which blocks the passwords suggested by chrome):

![image](https://user-images.githubusercontent.com/2439659/116515724-f3158280-a8cc-11eb-8b1a-d1ed1725127f.png)

**Comment by AnaBoscaneanu** [comment]
Thank you for the feedback!
Now the password policy is changed so it does not require special characters and the user can use chrome suggested passwords.

**Comment by anulaibar** [comment]
@AnaBoscaneanu Looks great!
